### ISSUE TITLE
non-overlap nodes

### ISSUE THREAD

**Issue by huashan** [analyxcompany/ForceAtlas2#1]
Hi, Thanks for this great package.

I just wonder it's possible to add node size as paramater, and get a layout without nodal overlap?

Thanks

**Comment by adolfoalvarez** [comment]
Hi @huashan thanks for your comment. We are trying to keep FA2 compatible with the igraph package, where the node sizes are stored in the igraph object and not in the layout. In a similar way, a potential "prevent overlap" parameter should not be included in the layout but in in the plot function, since it will depend on the nodes and labels sizes. I think there are plans to implement it given this: https://github.com/igraph/rigraph/issues/94.

Nevertheless, I think this feature is necessary so we will consider to contribute or write our own plot function including the "prevent overlap" parameter.

Best regards!
Adolfo.
