### ISSUE TITLE
Using the avoid overlap option

### ISSUE THREAD

**Issue by cafeine05** [analyxcompany/ForceAtlas2#2]
Hi,

First it all thank you for your work, it helps me a lot. I was wondering if there was a way to use in your package the avoid overlap function available in gephi and in the paper describing force Atlas.

Thank you

**Comment by adolfoalvarez** [comment]
@cafeine05 Hi! Thank you for your comment! As a general answer I will refer you to issue #1 , where in summary the layout and the plotting are two different and separate steps, for example you can always reduce the node size to get non overlapping nodes. I know this is not the perfect solution, but for now we don't have plans to implement a graphical function for FA2 (where we could address this issue). If instead of igraph you would like to use ggplot to plot your network, then I can recommend you the ggrepel package, that maybe could help. https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html

I'm sorry for that! Best regards,
Adolfo.
